GET http://localhost:3000/students
Content-Type: application/json

###

POST http://localhost:3000/students
Content-Type: application/json

{
  "nama": "febriadji",
  "fakultas": "teknologi informasi",
  "jurusan": "teknik informatika",
  "umur": 19,
  "kelamin": "laki-laki"
}

###

PUT http://localhost:3000/students/4
Content-Type: application/json

{
  "nama": "febriadji",
  "fakultas": "teknologi informasi",
  "jurusan": "teknik informatika",
  "umur": 18,
  "kelamin": "laki-laki"
}

### 

DELETE http://localhost:3000/students/4
Content-Type: application/json